import type { ContentItem } from "../types/database";
import type { Persona } from "./personas";

function cloneJson<T>(value: T): T {
  if (value == null) return value;
  return JSON.parse(JSON.stringify(value)) as T;
}

function cloneCard(card: ContentItem): ContentItem {
  return {
    ...card,
    metadata: cloneJson(card.metadata),
    source_bundle: cloneJson(card.source_bundle),
  };
}

const DEMO_CARDS: ContentItem[] = [
  {
    id: "demo-support-bulk-import",
    business_id: "demo-acme",
    session_id: "demo-support",
    content_type: "support",
    channel: "intercom",
    review_mode: "support",
    source_type: "thread",
    title: "Bulk import welcome email escalation",
    body_text:
      "Hi Peter,\n\nGood news, the bulk import trigger does support per-contact personalization. When the `bulk_import.completed` event fires, it includes the contact IDs so your workflow can iterate through each person individually.\n\nHere’s the cleanest setup:\n1. Change the trigger from `contact.created` to `bulk_import.completed`\n2. Add a `For Each Contact` step after the trigger\n3. Reuse your existing welcome template inside the loop so merge tags resolve per contact\n\nI can send over a sample workflow JSON if that helps.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "TKT-2048",
    source_bundle: null,
    prompt_input_summary: "Customer asked whether bulk imports can still send personalized welcome emails",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: {
      conversation: {
        customer: { name: "Peter Klutte", email: "peter@acme.io" },
        channel: "intercom",
        ai_confidence: 0.94,
        messages: [
          {
            role: "customer",
            text:
              "Ok that makes sense, but we also need to send personalized welcome emails per contact, not a single batch notification. Can the bulk trigger still do that?",
            timestamp: "2026-03-21T07:52:00.000Z",
            sender_name: "Peter Klutte",
          },
          {
            role: "bot",
            text:
              "I'm not able to confirm whether the bulk import trigger supports per-contact personalization in workflows. Let me escalate this to someone who can help.",
            timestamp: "2026-03-21T07:52:30.000Z",
            sender_name: "Fin AI",
            status: "failed",
          },
          {
            role: "customer",
            text:
              "Please do, this is blocking our onboarding flow for new users. We have 200+ contacts queued up waiting for welcome emails.",
            timestamp: "2026-03-21T07:55:00.000Z",
            sender_name: "Peter Klutte",
          },
        ],
      },
    },
    created_at: "2026-03-21T07:56:00.000Z",
    updated_at: "2026-03-21T07:56:00.000Z",
  },
  {
    id: "demo-social-launch-post",
    business_id: "demo-acme",
    session_id: "demo-social",
    content_type: "social",
    channel: "linkedin",
    review_mode: "social",
    source_type: "campaign",
    title: "Launch post for AI inbox triage",
    body_text:
      "Most support teams are still stitching together macros, tags, and hope.\n\nWe built a triage layer that reads the thread, drafts the next best reply, and flags risk before it hits your queue.\n\nThe result:\n- Faster first response times\n- Cleaner escalation paths\n- More confidence for every frontline rep\n\nWe’re opening up a small pilot group next month. Comment `triage` if you want early access.",
    script: null,
    image_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    source_ref: "CMP-101",
    source_bundle: null,
    prompt_input_summary: "LinkedIn launch announcement for support AI workflow product",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: true,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:05:00.000Z",
    updated_at: "2026-03-21T08:05:00.000Z",
  },
  {
    id: "demo-video-founder-reel",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "tiktok",
    review_mode: "video",
    source_type: "brief",
    title: "Founder reel: what support agents actually need from AI",
    body_text:
      "Fast-cut founder monologue with product UI inserts. Tone is sharp, direct, and optimistic.",
    script:
      "Hook: Most AI support tools are built for dashboards, not for the person answering the ticket.\n\nBeat 1: Show the moment an agent opens a chaotic thread.\nBeat 2: Overlay a draft reply, risk flags, and next-step suggestions.\nBeat 3: Founder to camera: 'The goal is not to replace the rep. It’s to make every rep feel like your best one.'\n\nClose on the product and a waitlist CTA.",
    image_url: null,
    video_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
    source_ref: "BRF-77",
    source_bundle: null,
    prompt_input_summary: "Short founder-led product teaser for TikTok and Reels",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "veo-3.1",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:12:00.000Z",
    updated_at: "2026-03-21T08:12:00.000Z",
  },
  {
    id: "demo-support-saml",
    business_id: "demo-acme",
    session_id: "demo-support",
    content_type: "support",
    channel: "intercom",
    review_mode: "support",
    source_type: "thread",
    title: "SAML certificate rollover diagnosis",
    body_text:
      "Hi James,\n\nI found the issue. Our validator still had your previous certificate stored as the primary signer, so it was rejecting the new response before trying the rotated one.\n\nI’ve cleared the stale certificate path and reset the cached SAML session on our side. Please try signing in again now. If it still fails, send me the timestamp of the next attempt and I’ll pull the trace immediately.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "TKT-1981",
    source_bundle: null,
    prompt_input_summary: "Enterprise SAML login issue after cert rollover",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: {
      conversation: {
        customer: { name: "James Okafor", email: "james@driftwood.io" },
        channel: "intercom",
        ai_confidence: 0.88,
        messages: [
          {
            role: "customer",
            text:
              "ACS URL is correct. We only rotated the signing certificate. We do not use encryption, and Okta is NTP-synced.",
            timestamp: "2026-03-21T08:08:00.000Z",
            sender_name: "James Okafor",
          },
          {
            role: "agent",
            text:
              "I’m on it. I can already see a likely mismatch in the certificate validation order. Give me a couple minutes to confirm.",
            timestamp: "2026-03-21T08:12:00.000Z",
            sender_name: "Ethan Huang",
          },
        ],
      },
    },
    created_at: "2026-03-21T08:16:00.000Z",
    updated_at: "2026-03-21T08:16:00.000Z",
  },
  {
    id: "demo-social-customer-story",
    business_id: "demo-acme",
    session_id: "demo-social",
    content_type: "social",
    channel: "twitter",
    review_mode: "social",
    source_type: "customer-story",
    title: "Customer story thread for onboarding wins",
    body_text:
      "A customer imported 200+ contacts and expected onboarding to stall.\n\nInstead, every welcome email still went out personalized, in sequence, and with zero manual cleanup.\n\nThat’s the difference between 'bulk action' and 'bulk action with the right workflow model.'\n\nProduct details matter.",
    script: null,
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    source_ref: "SOC-318",
    source_bundle: null,
    prompt_input_summary: "Short customer-proof social thread",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4-mini",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:22:00.000Z",
    updated_at: "2026-03-21T08:22:00.000Z",
  },
  {
    id: "demo-video-product-tour",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "instagram",
    review_mode: "video",
    source_type: "brief",
    title: "Product tour: from messy thread to clean draft",
    body_text:
      "Screen-recording style walkthrough with annotations on confidence scoring and escalation moments.",
    script:
      "Open on a noisy inbox. Zoom into the exact customer ask. Show the draft reply being assembled line by line, then pause on the risk badge and escalation suggestion. End with the line: 'Less queue triage. More real customer work.'",
    image_url: null,
    video_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
    thumbnail_url: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-21",
    source_bundle: null,
    prompt_input_summary: "Annotated product tour for Instagram reels",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: true,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "veo-3.1",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:28:00.000Z",
    updated_at: "2026-03-21T08:28:00.000Z",
  },
  {
    id: "demo-support-rate-limit",
    business_id: "demo-acme",
    session_id: "demo-support",
    content_type: "support",
    channel: "intercom",
    review_mode: "support",
    source_type: "thread",
    title: "API rate limit 429 errors during sync",
    body_text:
      "Hi Sarah,\n\nThe 429 errors you're seeing are caused by the sync job firing requests without backoff. Our API enforces a 100 req/min limit per API key, and your sync is exceeding that during the nightly batch.\n\nTwo quick fixes:\n1. Enable exponential backoff in your sync client config — set `retry.backoff_multiplier` to 2\n2. Stagger the sync window across your three workspaces so they don't all fire at midnight UTC\n\nI've also temporarily raised your rate limit to 200 req/min for the next 48 hours so nothing is blocked while you adjust.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "TKT-2103",
    source_bundle: null,
    prompt_input_summary: "Customer hitting API rate limits during nightly sync",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: {
      conversation: {
        customer: { name: "Sarah Lin", email: "sarah@northbeam.co" },
        channel: "intercom",
        ai_confidence: 0.91,
        messages: [
          {
            role: "customer",
            text:
              "We keep getting 429 errors every night around 12:05 AM UTC. Our sync job runs across three workspaces and they all kick off at the same time. Is there a rate limit we're hitting?",
            timestamp: "2026-03-21T08:30:00.000Z",
            sender_name: "Sarah Lin",
          },
          {
            role: "bot",
            text:
              "It looks like your API key is exceeding the rate limit. Let me connect you with someone who can help adjust your configuration.",
            timestamp: "2026-03-21T08:30:30.000Z",
            sender_name: "Fin AI",
            status: "failed",
          },
        ],
      },
    },
    created_at: "2026-03-21T08:32:00.000Z",
    updated_at: "2026-03-21T08:32:00.000Z",
  },
  {
    id: "demo-social-hiring-post",
    business_id: "demo-acme",
    session_id: "demo-social",
    content_type: "social",
    channel: "linkedin",
    review_mode: "social",
    source_type: "campaign",
    title: "We're hiring: Senior Support Engineer",
    body_text:
      "We're looking for a Senior Support Engineer who thinks about customer problems like a product person.\n\nYou won't be closing tickets. You'll be:\n→ Diagnosing workflows and recommending better setups\n→ Building internal tools that make the team faster\n→ Turning repeated questions into documentation that actually helps\n\nIf you've ever thought 'there should be a better way to handle this,' we want to talk.\n\nRemote · Full-time · Link in comments",
    script: null,
    image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80",
    source_ref: "CMP-109",
    source_bundle: null,
    prompt_input_summary: "LinkedIn hiring post for Senior Support Engineer role",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:38:00.000Z",
    updated_at: "2026-03-21T08:38:00.000Z",
  },
  {
    id: "demo-video-customer-testimonial",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "youtube",
    review_mode: "video",
    source_type: "brief",
    title: "Customer testimonial: Northbeam support transformation",
    body_text:
      "Interview-style cut with the Head of Support at Northbeam. B-roll of their team using the product in real time.",
    script:
      "Cold open: 'We went from a 4-hour average first response to under 20 minutes.'\n\nInterview segment 1: What was the support stack before?\nInterview segment 2: What changed after adopting the AI triage layer?\nB-roll: Live screen capture of draft review flow\n\nClosing: 'It's not about fewer people. It's about better answers, faster.'\n\nEnd card with logo + CTA.",
    image_url: null,
    video_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-34",
    source_bundle: null,
    prompt_input_summary: "Customer testimonial video for YouTube featuring Northbeam",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "veo-3.1",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:44:00.000Z",
    updated_at: "2026-03-21T08:44:00.000Z",
  },
  {
    id: "demo-support-webhook-failure",
    business_id: "demo-acme",
    session_id: "demo-support",
    content_type: "support",
    channel: "intercom",
    review_mode: "support",
    source_type: "thread",
    title: "Webhook delivery failures after DNS migration",
    body_text:
      "Hi Marcus,\n\nI traced the webhook failures to a DNS propagation issue. Your endpoint `hooks.revflow.io` currently resolves to the old IP (34.102.x.x) from our delivery servers, even though your DNS records have been updated.\n\nOur webhook infrastructure caches DNS for up to 30 minutes. I've manually flushed the cache for your endpoint. The next retry cycle should pick up the new IP.\n\nI'll monitor the delivery queue for the next hour and confirm once all pending events have been successfully delivered. You should see the backlog clear within 15–20 minutes.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "TKT-2087",
    source_bundle: null,
    prompt_input_summary: "Webhook deliveries failing after customer DNS migration",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: true,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: {
      conversation: {
        customer: { name: "Marcus Chen", email: "marcus@revflow.io" },
        channel: "intercom",
        ai_confidence: 0.86,
        messages: [
          {
            role: "customer",
            text:
              "We migrated our DNS to Cloudflare yesterday and now none of our webhooks are coming through. The endpoint URL hasn't changed, just the underlying IP. Our logs show zero incoming requests since 3 PM yesterday.",
            timestamp: "2026-03-21T08:40:00.000Z",
            sender_name: "Marcus Chen",
          },
          {
            role: "bot",
            text:
              "I can see webhook delivery attempts are failing with connection timeouts. This may be related to DNS propagation. Let me escalate to our infrastructure team.",
            timestamp: "2026-03-21T08:40:45.000Z",
            sender_name: "Fin AI",
            status: "escalated",
          },
        ],
      },
    },
    created_at: "2026-03-21T08:48:00.000Z",
    updated_at: "2026-03-21T08:48:00.000Z",
  },
  {
    id: "demo-social-product-update",
    business_id: "demo-acme",
    session_id: "demo-social",
    content_type: "social",
    channel: "twitter",
    review_mode: "social",
    source_type: "campaign",
    title: "Product update: confidence scoring shipped",
    body_text:
      "Shipped: every AI draft reply now shows a confidence score.\n\nGreen = high confidence, send with one click\nYellow = review suggested, context might be ambiguous\nRed = escalate, the model isn't sure\n\nYour team sees the signal before they decide. No guessing.\n\nRolling out to all accounts this week.",
    script: null,
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    source_ref: "SOC-325",
    source_bundle: null,
    prompt_input_summary: "Product update announcement for confidence scoring feature",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: true,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4-mini",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:52:00.000Z",
    updated_at: "2026-03-21T08:52:00.000Z",
  },
  {
    id: "demo-support-data-export",
    business_id: "demo-acme",
    session_id: "demo-support",
    content_type: "support",
    channel: "intercom",
    review_mode: "support",
    source_type: "thread",
    title: "Data export timing out for large accounts",
    body_text:
      "Hi Priya,\n\nThe timeout on your CSV export is happening because the query is pulling 14 months of interaction data without any date filter. Our export endpoint has a 60-second timeout, and your dataset exceeds what can be serialized in that window.\n\nHere's what I recommend:\n1. Use the `date_from` and `date_to` params to export in 3-month chunks\n2. For the full dataset, use our async bulk export endpoint at `/v2/exports/bulk` — it runs in the background and emails you a download link\n\nI've attached the API docs for the bulk endpoint. Let me know if you'd like me to trigger a full export on your behalf.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "TKT-2115",
    source_bundle: null,
    prompt_input_summary: "Customer data export timing out due to large dataset",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: {
      conversation: {
        customer: { name: "Priya Sharma", email: "priya@cloudlane.dev" },
        channel: "intercom",
        ai_confidence: 0.92,
        messages: [
          {
            role: "customer",
            text:
              "I'm trying to export all our interaction data as CSV but the request keeps timing out. We have about 14 months of data. Is there a size limit?",
            timestamp: "2026-03-21T08:55:00.000Z",
            sender_name: "Priya Sharma",
          },
        ],
      },
    },
    created_at: "2026-03-21T08:58:00.000Z",
    updated_at: "2026-03-21T08:58:00.000Z",
  },
  {
    id: "demo-video-explainer-confidence",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "tiktok",
    review_mode: "video",
    source_type: "brief",
    title: "Explainer: how confidence scoring works",
    body_text:
      "Animated explainer breaking down the three confidence tiers with real examples from support threads.",
    script:
      "Hook: 'Your AI just wrote a reply. But should you send it?'\n\nScene 1: Show a green-scored reply — simple billing question, high match. One-click send.\nScene 2: Show a yellow-scored reply — ambiguous refund policy edge case. Model suggests review.\nScene 3: Show a red-scored reply — legal question about data deletion. Auto-escalation triggered.\n\nVoiceover: 'Confidence scoring gives your team a signal, not a guess.'\n\nEnd with product logo and sign-up link.",
    image_url: null,
    video_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-39",
    source_bundle: null,
    prompt_input_summary: "Animated explainer for confidence scoring feature on TikTok",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "veo-3.1",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T09:02:00.000Z",
    updated_at: "2026-03-21T09:02:00.000Z",
  },
  {
    id: "demo-social-industry-take",
    business_id: "demo-acme",
    session_id: "demo-social",
    content_type: "social",
    channel: "linkedin",
    review_mode: "social",
    source_type: "thought-leadership",
    title: "Hot take: why CSAT is a lagging indicator",
    body_text:
      "CSAT scores tell you how customers felt. Not how your team performed.\n\nA 4.8 CSAT with a 6-hour first response? That's a patient customer, not a good process.\n\nLeading indicators that actually matter:\n• Time to first meaningful reply (not auto-ack)\n• Escalation accuracy — did the right person get it?\n• Draft acceptance rate — are AI suggestions actually useful?\n\nStop celebrating the score. Start measuring the system.",
    script: null,
    image_url: null,
    video_url: null,
    thumbnail_url: null,
    source_ref: "SOC-331",
    source_bundle: null,
    prompt_input_summary: "Thought leadership LinkedIn post on support metrics",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gpt-5.4",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T09:08:00.000Z",
    updated_at: "2026-03-21T09:08:00.000Z",
  },
  {
    id: "demo-video-before-after",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "instagram",
    review_mode: "video",
    source_type: "brief",
    title: "Before/after: support inbox transformation",
    body_text:
      "Split-screen comparison showing a chaotic inbox vs. the same inbox with AI triage active.",
    script:
      "Left side: Unorganized inbox. 47 unread. No priority signals. Agent scrolling, guessing which ticket matters.\n\nRight side: Same inbox, AI triage on. Color-coded priority. Draft replies pre-loaded. Risk flags visible. Agent clicks into the top ticket and sends in 30 seconds.\n\nText overlay: 'Same team. Same volume. Different system.'\n\nEnd card with demo CTA.",
    image_url: null,
    video_url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-42",
    source_bundle: null,
    prompt_input_summary: "Before/after split-screen comparison for Instagram",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "veo-3.1",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T09:14:00.000Z",
    updated_at: "2026-03-21T09:14:00.000Z",
  },
];

export function getSeededDemoCards(persona: Persona): ContentItem[] {
  return DEMO_CARDS
    .filter((card) => persona.contentTypes.includes(card.content_type))
    .map(cloneCard)
    .sort(
      (a, b) =>
        new Date(a.created_at ?? 0).getTime() -
        new Date(b.created_at ?? 0).getTime()
    );
}

