import type { ContentItem } from "../types/database";
import type { Persona } from "./personas";

function cloneJson<T>(value: T): T {
  if (value == null) return value;
  return JSON.parse(JSON.stringify(value)) as T;
}

function cloneCard(card: ContentItem): ContentItem {
  return {
    ...card,
    metadata: cloneJson(card.metadata),
    source_bundle: cloneJson(card.source_bundle),
  };
}

const DEMO_CARDS: ContentItem[] = [
  {
    id: "demo-video-resonate-reel",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "instagram",
    review_mode: "video",
    source_type: "brief",
    title: "AI Models on a Crashing Plane",
    body_text:
      "Stylized 3D comedy reel — what happens when AI models are passengers on a crashing plane. Each model reacts in character.",
    script:
      "Setup: A plane is going down. Each AI model reacts differently.\n\nGPT-4: Calmly pulls out a parachute labeled 'GPT-4o emergency kit' and explains exit procedure.\nClaude: Offers its parachute to the person next to it.\nLlama: Already jumped — open source, no permission needed.\nGrok: Live-tweeting the crash.\nGemini: Alone in first class, muscles bulging, takes the only remaining parachute.\n\nClose: Gemini hands the harness to a passenger. Opens Google Docs. Begins writing his own eulogy.",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/uploads/resonate-reel-1774112768901.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-84",
    source_bundle: null,
    prompt_input_summary: "Comedy reel — AI models as people on a crashing plane",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: true,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:12:00.000Z",
    updated_at: "2026-03-21T08:12:00.000Z",
  },
  {
    id: "demo-video-vibe-coder",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "tiktok",
    review_mode: "video",
    source_type: "brief",
    title: "Day in the Life of a Vibe Coder",
    body_text:
      "Stylized 3D slideshow reel — a day following a vibe coder from morning standup to midnight deploy.",
    script:
      "Morning: Check Slack, mass-mark as read. Open VS Code, stare at a function named 'doStuff'.\nUnderstanding: Read the same 4 lines of code for 20 minutes. Mass-highlight, delete, rewrite identically.\nNew feature: Ship it to prod. It works. No tests. No idea why.\nLunch: Ramen. Still thinking about that one variable name.\nAfternoon: A batch job runs. Hands off keyboard. Don't touch anything.\nExplaining: At the whiteboard. Vague arrows. 'It's like a pipeline but not really.'\nOne small change: Press one key. Everything breaks. Everything also fixes itself.\nClose: Laptop gently closes. Tomorrow we vibe again.",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/uploads/1774113370285-vibe-coder-reel-1.4x.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-91",
    source_bundle: null,
    prompt_input_summary: "Day-in-the-life comedy reel for vibe coders",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:28:00.000Z",
    updated_at: "2026-03-21T08:28:00.000Z",
  },
  {
    id: "demo-video-cv-ad",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "instagram",
    review_mode: "video",
    source_type: "brief",
    title: "Where AI Builders Go — Cerebral Valley",
    body_text:
      "Fast-paced 20s video ad for Cerebral Valley — hook, credibility, value prop, CTA.",
    script:
      "Hook (3s): Rapid cuts of founders, terminals, neural nets training.\nCredibility (4s): Packed venue shots, hackathon energy.\nValue (7s): Real conversations, live demos, the community that ships.\nPositioning (5s): Dark-mode event platform, diverse builders entering the venue.\nCTA (3s): CEREBRAL VALLEY — bold text on black. Join the builders.",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/uploads/1774114548692-cv-ad.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-103",
    source_bundle: null,
    prompt_input_summary: "20-second Instagram ad for Cerebral Valley AI community",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:35:00.000Z",
    updated_at: "2026-03-21T08:35:00.000Z",
  },
  {
    id: "demo-video-acme-coffee",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "tiktok",
    review_mode: "video",
    source_type: "brief",
    title: "Acme Coffee Co: Elevate Your Morning Ritual",
    body_text:
      "Product showcase reel with smooth transitions between coffee-making steps and lifestyle moments.",
    script:
      "Open on beans cascading into a grinder. Close-up of steam curling from a fresh pour.\nCut to hands wrapping around a mug, morning light through the window.\nProduct shot with packaging. Text overlay: 'Sourced directly. Roasted weekly.'\nCTA: 'Elevate your morning — link in bio.'",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/generated/545ebfba-d9c6-4441-beb1-786caea9cc56.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-12",
    source_bundle: null,
    prompt_input_summary: "Coffee brand product reel for TikTok",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:42:00.000Z",
    updated_at: "2026-03-21T08:42:00.000Z",
  },
  {
    id: "demo-video-geodude-ad",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "youtube",
    review_mode: "video",
    source_type: "brief",
    title: "GEODUDE™ Infomercial — Stability You Can Trust",
    body_text:
      "Ultra-serious dramatic infomercial treating Geodude as a premium product. Military-grade sincerity meets rock-solid absurdity.",
    script:
      "Hook: \"Are you tired of being physically limited?\" — groceries falling in slow-mo.\nReveal: Geodude floats beside customer like a luxury product.\nTitle card: \"INTRODUCING GEODUDE™ — OWN THE EARTH\"\nMontage: Geodude lifts a car, smashes a door, hovers in a boardroom.\nFeatures: STRENGTH. PROTECTION. PRESENCE.\nBenefits: No batteries. No training required. No questions asked.\nTestimonial: \"Before Geodude… I had fear. Now… I have Geodude.\"\nOffer: MULTIPLE GEODUDES — limited time.\nLifestyle: Mountain cliff sunset with Geodude squad.\nCTA: \"Call now. Claim your Geodude. Stability you can trust.\"",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/uploads/1774120280331-geodude-ad.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-120",
    source_bundle: null,
    prompt_input_summary: "Pokémon infomercial — Geodude as premium product, ultra-serious tone",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: null,
    metadata: null,
    created_at: "2026-03-21T08:45:00.000Z",
    updated_at: "2026-03-21T08:45:00.000Z",
  },
  {
    id: "demo-video-resonate-fast",
    business_id: "demo-acme",
    session_id: "demo-video",
    content_type: "video",
    channel: "tiktok",
    review_mode: "video",
    source_type: "brief",
    title: "AI Models on a Crashing Plane (Fast Cut)",
    body_text:
      "1.4x speed version of the AI models comedy reel — punchier timing for short-form platforms.",
    script:
      "Same narrative as the original — GPT-4, Claude, Llama, Grok, Gemini reacting to a plane crash — but cut at 1.4x speed for TikTok attention spans. Every beat hits faster.",
    image_url: null,
    video_url: "https://rnqkjfrwkyupkyvygtpg.supabase.co/storage/v1/object/public/content-videos/uploads/1774113610235-resonate-reel-1.4x.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80",
    source_ref: "VID-85",
    source_bundle: null,
    prompt_input_summary: "Fast-cut version of AI models comedy reel for TikTok",
    review_status: "pending",
    review_note: null,
    reviewed_by: null,
    reviewed_at: null,
    starred: false,
    down_arrow_designation: null,
    generation_job_id: null,
    generation_status: "completed",
    model_name: "gemini-2.5-pro",
    prompt_template_id: null,
    parent_id: null,
    variant_of: "demo-video-resonate-reel",
    metadata: null,
    created_at: "2026-03-21T08:50:00.000Z",
    updated_at: "2026-03-21T08:50:00.000Z",
  },
];

export function getSeededDemoCards(persona: Persona): ContentItem[] {
  return DEMO_CARDS
    .filter((card) => persona.contentTypes.includes(card.content_type))
    .map(cloneCard)
    .sort(
      (a, b) =>
        new Date(a.created_at ?? 0).getTime() -
        new Date(b.created_at ?? 0).getTime()
    );
}
